# Generated by Django 4.1.7 on 2023-05-08 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0002_amenities_configuration_gallery_overview_walkthrough'),
    ]

    operations = [
        migrations.AddField(
            model_name='overview',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='overview',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
