# Generated by Django 4.1 on 2023-05-10 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0007_know_your_locality_alter_enquire_now_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire_now',
            name='enquiry_type',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
