# Generated by Django 4.1 on 2023-05-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0009_alter_know_your_locality_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walkthrough',
            name='video',
            field=models.TextField(default='https://www.youtube.com/embed/6HeE9W2bR-I'),
        ),
    ]
