# Generated by Django 4.1 on 2023-05-11 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0010_alter_walkthrough_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='locality_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField(default='https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d3806.012976551304!2d78.429541!3d17.459093!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0xd4a220dc7610156d!2sBrigade%20Citadel!5e0!3m2!1sen!2sin!4v1632476420684!5m2!1sen!2sin&rel=0')),
            ],
        ),
    ]
