# Generated by Django 4.2.1 on 2023-05-13 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0011_locality_map'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='images',
        ),
        migrations.RemoveField(
            model_name='overview',
            name='image',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(default='', upload_to='gallery_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='web_image',
            field=models.ImageField(default='', upload_to='gallery_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='png_image',
            field=models.ImageField(default='', upload_to='overview_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='overview',
            name='webp_image',
            field=models.ImageField(default='', upload_to='overview_images'),
            preserve_default=False,
        ),
    ]
