# Generated by Django 4.1 on 2023-05-15 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0012_remove_gallery_images_remove_overview_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='images',
            field=models.ImageField(upload_to='amenities_images'),
        ),
    ]
