# Generated by Django 4.1 on 2023-05-15 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0013_alter_amenities_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='amenities',
            old_name='images',
            new_name='image',
        ),
    ]
