# Generated by Django 4.1 on 2023-05-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0014_rename_images_amenities_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_logo', models.ImageField(upload_to='logo_images')),
                ('secondary_logo', models.ImageField(upload_to='logo_images')),
            ],
        ),
    ]
