# Generated by Django 4.1 on 2023-05-15 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Brigadeapp', '0015_logos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Logos',
            new_name='Logo',
        ),
    ]
